name: Test get_started example
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '30 22 * * 0'

permissions: 
  actions: read
  security-events: write

jobs:
  build-and-run:
    
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'    

      - name: Install system packages
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install libpython3.9 libtinfo5

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1
  
      - name: Build
        run: |
          echo "Building get started example ..."
          cbuild get_started.csolution.yml --packs --update-rte --context .debug+avh --toolchain ARMCLANG

      - name: Execute
        run: |
          echo "Running get started example ..."
          FVP_MPS2_Cortex-M3 --simlimit 10 -f fvp-config.txt -a out/Project/ARMCM3/Debug/Project.axf | tee model.log
          echo "Checking output..."
          grep "Hello World" model.log | wc -l
          test "$(grep "Hello World" model.log | wc -l)" -eq 10