name: Test get_started Unit Tests  
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '30 22 * * 0'

permissions: 
  contents: read
  actions: read
  checks: write

jobs:
  ci_run:
    
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'    

      - name: Install system packages
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install libpython3.9 libtinfo5
          pip install junit_reporter

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1
  
      - name: Build
        run: |
          echo "Building get started example ..."
          cbuild get_started.csolution.yml --packs --update-rte --context .debug+avh 

      - name: Execute
        run: |
          echo "Running get started example ..."
          FVP_MPS2_Cortex-M3 --simlimit 10 -f Project/fvp_config.txt -a out/Project/avh/debug/Project.elf | tee Project.avh.log

      - name: Convert log to junit
        run: |
          echo "Converting log to junit..."
          python Project/report.py Project.avh.log
      
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
            name: Project Unit Test Report from AVH run           # Name of the check run which will be created
            path: Project.avh.xml     # Path to test results
            reporter: jest-junit        # Format of test results
